version: "3.8"
services:
  file-service:
    container_name: file-service
    image: file-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8084:8084"
    networks:
      - wavshare-nw

networks:
  wavshare-nw:
    external:
      name: wavshare-nw